### ISSUE TITLE
[BUG] f_is_def() does not work with filter()

### ISSUE THREAD

**Issue by pipatron** [BelfrySCAD/BOSL2#1202]
`f_is_def()` does not work as expected, a simple example:
```
include <BOSL2/std.scad>
include <BOSL2/fnliterals.scad>

v = [ 1, undef, 2, undef, 3 ];

f1 = function(x) is_def(x);
f2 = f_is_def();

v1 = filter( f1,         v );
v2 = filter( f2,         v );
v3 = filter( f_is_def(), v );

echo(v1=v1);
echo(v2=v2);
echo(v3=v3);
```
Result using 9cbfa540bd6100a7e1406952d7a4c64ca158c8ee with both OpenSCAD 2023.07.09.nightly and 2021.01:
```
ECHO: v1 = [1, 2, 3]
ECHO: v2 = [1, undef, 2, undef, 3]
ECHO: v3 = [1, undef, 2, undef, 3]
```
I would have assumed all three vectors were identical, but I can't figure out how to use `f_is_def()`. Is it a problem with my usage or is there an actual bug?

**Comment by adrianVmariano** [comment]
It looks like fn_is_def() is returning a function-valued function instead of a boolean valued function.  It's value is therefore always true.   I think that's a bug...though I may not quite understand how it's supposed to work, so maybe I'm missing something.  

I wouldn't be surprised if the fnliterals stuff is full of issues.  I would guess that testing of that code has been quite shallow.  Revar wrote it because he was excited by the addition of function literalas and it seemed like a good idea, but I don't think we've ever actually found a practical use for any of it.
