### ISSUE TITLE
Bezier solids?

### ISSUE THREAD

**Issue by iloving** [BelfrySCAD/BOSL2#1321]
**Is your feature request related to a problem? Please describe.**
I want to create a complex curved wall that is a bezier surface but 2mm thick, but it is time consuming to meticulously construct all the sides.

**Describe the solution you'd like**
There are many modules and functions that extrude polygons along paths and even bezier curves, but there is nothing for bezier patches

Not sure what the simplest option is... maybe a bezier patch equivalent of path_copies?

**Describe alternatives you've considered**
Constructing each side individually

**Example Code**
```
// Code goes here.
```

**Additional context**
I've attached a screenshot of the kind of object I'm trying to create.

<img width="388" alt="image" src="https://github.com/BelfrySCAD/BOSL2/assets/1250003/0340bb0e-b69c-46a3-8667-2e2e6354a7f2">

**Comment by adrianVmariano** [comment]
I don't understand what you are trying to do.  You want to put together several copies of that bezier patch?  You want to make that shape 2mm thick, like a warped sheet?  We need more information.  What would the ideal (but possibly unrealistic or impractical) capability look like?  What would a "do_what_I_need()" function do to help with the above.  

The path_copies function puts an object at points on a path.  If there were a bezier_patch version it would presumably put an object over some sort of grid on the bezier patch.  That doesn't sound related at all to your needs.

**Comment by adrianVmariano** [comment]
The task of making the edges is fussy, but really not difficult.  The task of making an offset second patch is I think trickier.  The way to do it is make the VNF and then make the second VNF by shifting the points individually based on the patch normals.   

I can't think of a way that your idea of copying some primitive object to all the points would make any sense.  What is needed is to construct the faces, either by figuring out the face list coordinates from the combined VNF of both sides, or by extracting the points from both bezier patch boundaries and then using vnf_vertex_array.

**Comment by revarbat** [comment]
Off the top of my head, I'd convert the bezier surface into a grid of 3D points, make a copy of that and `move()` it to be the bottom, reverse it, concat it to the original set of points, and pass the whole thing to `vnf_vertex_array()` with row_wrap and caps.

**Comment by revarbat** [comment]
There is merit to having a `vnf_loft()` function to do all that, though.

**Comment by adrianVmariano** [comment]
I already suggested making a translated reversed copy, @revarbat , but that doesn't make a uniformly thick surface.  It will vary in thickness depending on the curves of the bezier patch.  I also don't understand how your proposed use of vnf_vertex_array would work.  It seems like it would create a ton of internal faces everywhere, linking every point to every other point with a face, instead of just creating the boundary faces.  

If you make vnf_sweep() then you lose the derivative information that is in the bezier, which seems undesirable.  
(Is lofting different than sweeping?)

**Comment by revarbat** [comment]
I used "loft" as a verb because that's what another CAD I've used calls it when you take a surface and move it to make a thicker volume.  Anyways, I recently did a thing where I took a 2D grid with heights and lofted it to give it volume. (Though I called it extrude at the time.)

It abuses the endcap and col_wrap features of `vnf_vertex_array()` to get all four sides of the extrusion from the two bumpy faces.

```
function surf_extrude(surfpts, height) =
    vnf_vertex_array(
        [for (row=surfpts) concat(row, down(height, p=reverse(row)))],
        caps=true, col_wrap=true, row_wrap=false
    );
```

A true constant-thickness extrusion/lofting would be equivalent to implementing 3D `offset()` with all the error checking and face eliding that that implies.

**Comment by adrianVmariano** [comment]
I'm not following how surf_extrude() works.  Is surfpts a 2d array of points rather than just a list of vnf points?  

Yes, a robust constant thickness extrusion would be hard/impossible.  But a 2mm offset may be possible for many shapes that don't have very close points in the VNF.  In other words, the case where no points are deleted by the offset can be handled.

**Comment by revarbat** [comment]
`surfpts=` is indeed a 2D array of 3D points, just like you would feed to `vnf_vertex_array()`.

**Comment by revarbat** [comment]
Well, you can, for every vertex in the original surface, calculate the normals of all the faces surrounded that vertex, find the average of those normals, and use that normal for moving the vertex by a given distance.  If the faces aren't too small, you can get away without error checking.

**Comment by adrianVmariano** [comment]
Or, you know, if it's a bezier patch you can use the bezer_patch_normals() call which will give you exact normals.   That's a reason to want a bezier specific implementation.

**Comment by revarbat** [comment]
That sounds like an argument for `bezier_patch_offset()` as well as `vnf_offset()`.  :smile:

**Comment by revarbat** [comment]
Err, the fact that I had already had to write that function for a non-bezier case, suggests it'd be useful as well.

**Comment by revarbat** [comment]
I was working with 3D surface grids generated by computing combinations of 2D function outputs.

**Comment by revarbat** [comment]
Here's a very naive `vnf_offset()` with no error checking that offsets each vertex based on the averaged normals of the surrounding faces.  Getting from that to an extrusion/lofting function will take more work.

```openscad
function vnf_offset(vnf, dist) =
    let(
        verts = vnf[0],
        faces = vnf[1],
        face_planes = [
            for (face = faces)
            let(
                poly = [for (k = face) verts[k]],
                n = unit(polygon_normal(poly)),
                opoly = move(n*dist, p=poly)
            )
            plane_from_polygon(opoly)
        ],
        vert_faces = group_data(
            [for (i = idx(faces), vert = faces[i]) vert],
            [for (i = idx(faces), vert = faces[i]) i]
        ),
        vert_planes = [
            for (i = idx(verts))
            unique([ for (j = vert_faces[i]) face_planes[j] ])
        ],
        nuverts = [
            for (i = idx(verts))
            let(
                vert = verts[i],
                planes = vert_planes[i],
                lp = len(planes)
            )
            lp==0 ? vert :
            let(
                norms = [for (plane=planes) plane_normal(plane)],
                n = unit(sum(norms))
            )
            vert + dist*n
        ]
    )
    [nuverts, faces];
```
<img width="757" alt="Screenshot 2023-12-07 at 8 43 34 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/bf2456af-c54f-4d7c-97e6-86ecb66d3939">

**Comment by adrianVmariano** [comment]
A bezier version is simpler to implement, I think, since there's a function already available that computes exact normals.

**Comment by adrianVmariano** [comment]
Not sure if this is a good idea...but we could have an `offset=` arg for creating bezier surfaces.

**Comment by revarbat** [comment]
That seems rather elegant, actually.

**Comment by adrianVmariano** [comment]
bezier_sheet and vnf_sheet address this
