### ISSUE TITLE
[BUG] screw_head(screw_info("M4", head="flat")) crashes if (optional?) flat_height argument is not given

### ISSUE THREAD

**Issue by ovitters** [BelfrySCAD/BOSL2#1462]
**Describe the bug**
The [wiki](https://github.com/BelfrySCAD/BOSL2/wiki/screws.scad#module-screw_head) describes `screw_head` as just needing a `screw_info` data structure for it to work. If `screw_head` is called for a `screw_info` structure with argument `head="flat"`, it'll cause a crash/error message. This as `screw_head` assumes `flat_height` is given as an argument. 

The wiki has `flat_height` optional:
> Usage:
> 
>     screw_head(screw_info, [details],[counterbore],[flat_height],[teardrop],[internal])
> 

I updated BOSL2 from git, behaviour is still the same.

I'm guessing either `flat_height` needs to be calculated, or `flat_height` should not be optional?

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/screws.scad>

screw_head(screw_info("M4", head="flat"));

// This would work
//screw_head(screw_info("M4", head="flat"), flat_height=4);
```

**Expected behavior**
A screw head.

**Screenshots**
```
WARNING: undefined operation (undefined - number) in file screws.scad, line 1463 
WARNING: undefined operation (number * undefined) in file screws.scad, line 1465 
WARNING: undefined operation (number - undefined) in file screws.scad, line 1465 
WARNING: undefined operation (-undefined) in file screws.scad, line 1469 
WARNING: undefined operation (-undefined) in file screws.scad, line 1469 
WARNING: undefined operation (undefined + undefined) in file screws.scad, line 1469 
ERROR: Assertion 'is_num(fill)' failed in file coords.scad, line 78 
TRACE: called by 'path3d' in file skin.scad, line 461 
TRACE: called by 'skin' in file skin.scad, line 400 
TRACE: called by 'skin' in file screws.scad, line 1469 
TRACE: called by 'if' in file screws.scad, line 1458 
TRACE: called by 'union' in file screws.scad, line 1450 
TRACE: called by 'children' in file attachments.scad, line 2851 
TRACE: called by 'children' in file builtins.scad, line 22 
TRACE: called by 'if' in file builtins.scad, line 22 
TRACE: called by '_color' in file attachments.scad, line 2851 
TRACE: called by 'if' in file attachments.scad, line 2850 
TRACE: called by 'if' in file attachments.scad, line 2849 
TRACE: called by 'multmatrix' in file attachments.scad, line 2840 
```

**Additional context**
- OpenSCAD Version:  2021.01 
- Other libraries used: no

**Comment by adrianVmariano** [comment]
Strictly speaking, `flat_height` is optional because you only need to supply it if the screw is a flat head type.   

I'm not sure if this is a doc issue only, or if something needs to change so that you can get a default height.   Currently that height is computed in screw().  Why are you making a screw head alone rather than using screw()?

**Comment by adrianVmariano** [comment]
It looks like you're trying to put the head above the base portion of the model, which requires knowing the height of the head.  That means it wouldn't suffice for screw_head to have a default---the value needs to be extractable from the screw_info structure.

**Comment by adrianVmariano** [comment]
OpenSCAD can never tell you how large something is unless you already know how large it is (and saved the information).  

I would think you should be using screw_hole() to make the screw hole.  Here's maybe the best you can do as things stand.   With some fancy differencing I can create the right shape.  But I either have to guess the height of the cylinder so its end is in the middle of the model, or do like below and cut it off.    And this still relies on having access to the diameter of the head.  Without that there's no way to proceed.  So for something like this it seems like you really want flat_height to be in the screw_info structure.   But this is troublesome because the exact value of flat_height depends on $fn and on whether the screw is created as an internal (hole) or regular screw.   (In fact, when investigating this I realized it wasn't being computed quite correctly.)  


```
diff()
cuboid([20,20,5])
  tag("remove"){
    position(TOP)screw_hole(screw,length=15,anchor="head_bot")
      tag("") cyl(d=struct_val(screw,"head_size")+2, l=14);
    align(BOT)cuboid([20,20,20]);
}    
```

**Comment by adrianVmariano** [comment]
I suppose one question is why the raised portion needs to be sized to match the depth of the flat head.  It could really be any depth.

**Comment by adrianVmariano** [comment]
I added a note in the docs that flat_height is required for flat heads and a check that the parameter is given.
