### ISSUE TITLE
[BUG] Path_sweep() asymmetric behavior

### ISSUE THREAD

**Issue by dan-p3rry** [BelfrySCAD/BOSL2#1495]
**Describe the bug**
path_sweep() doesn't seem to be capable of sweeping both directions along an arc.

**Code To Reproduce Bug**
```
// Code goes here.
include <BOSL2/std.scad>
include <BOSL2/rounding.scad>

edge_shape = rect([2, 10], rounding=[1, 1, -2, 0], anchor=FRONT);

// these two are the same except order of points
corner_path1 = yrot(90, path3d(arc(r=2, start=180, angle=90, $fn=90)));
corner_path2 = yrot(90, path3d(arc(r=2, start=270, angle=-90, $fn=90)));

// both arcs are the same, except order of points
right(5) yrot(90) arc(r=2, start=180, angle=90, $fn=90);
right(10) yrot(90) arc(r=2, start=270, angle=-90, $fn=90);

// this is good
path_sweep(edge_shape, corner_path1);
// this is bad, I'm expecting mirror image of previous line.
left(10) path_sweep(edge_shape, corner_path2);

// mirror will solve the problem
left(20) mirror([1, 0, 0]) path_sweep(edge_shape, corner_path1);

// but how to implement inside a concat()?:
    // path = path_merge_collinear(
    //     concat( corner_path9,
    //         path3d(corner_path7),
    //         path3d(path1), path3d(corner_path1), 
    //         path3d(path2),
    //         path3d(corner_path2), path3d(path3), path3d(corner_path3), 
    //         path3d(path4), path3d(corner_path5), path3d(faucet_path),
    //         path3d(corner_path6), path3d(path5), corner_path8
    //     )
    // );
    // up(drainer_floor_thick) path_sweep(edge_shape, path);


**Expected behavior**
When 2D shape is non-symmetrical, I should be able to get mirror image 3D path sweep by sweeping in opposite direction.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
- OpenSCAD Version: Sept. 16, 2024
- Other libraries used:

**Comment by adrianVmariano** [comment]
I think your expectations are incorrect.  Think carefully about what it means to point the normal of your profile shape (the z axis) in the direction of the path.  When you change the path direction, it means the path normal points in the opposite direction.   So when you reverse the path it has to rotate the profile around 180 degrees to line up the normal of your profile with the reversed normal of the path.  The result SHOULD therefore be different.  

See Figures 1.5.1 and 1.5.2 in the path_sweep() manual section which show exactly this, with the remark that the sweep looks quite different if you go the opposite direction on the same path.

**Comment by dan-p3rry** [comment]
Actually figures 1.5.1 and 1.5.2 show what I want to happen (2d shape
mirrored), but my path/arc is rotating around X-axis instead of Z-axis, and
my output is not similar to figures 1.5.1 and 1.5.2.
[image: image.png]

The figure on the right is correct.  The arc rotates towards you from the
XZ plane to the XY plane and the 2D shape is swept along the outside of the
arc.
The figure on the left is incorrect (to me). The same arc rotates away from
you, from the XY plane up to the XZ plane.  The 2D shape is swept along the
*inside* of the arc, not the outside.  Is that the expected behavior?  I'm
kinda guessing here that the path_sweep() hasn't been developed with non-XY
plane arcs in mind.  I'm not sure how the path_sweep() function would even
know what is the correct side of the arc.

I can think of a couple work-arounds:  mirror the figure on the right, or
mirror the 2D shape that is swept, but neither of these works nicely with:

*path_sweep(my_2d_shape, path_merge_collinear( concat( my_list_of_paths)));*


Regards,
Dan

**Comment by adrianVmariano** [comment]
Ah, ok, so the issue has to do with twist, which is a fundamental ambiguity in the notion of a path sweep.  You are using the default method, "incremental".  In the section on that method from the manual:

To start the algorithm, we need an initial condition. This is supplied by using the normal argument to give a direction to align the Y axis of your shape. By default the normal points UP if the path makes an angle of 45 deg or less with the xy plane and it points BACK if the path makes a higher angle with the XY plane.

So the initial twist direction end up different when you start at one end of the circle than the other.  You can solve this by specifying the desired initial direction with normal=, or you can switch to the "natural" method (which requires a 90 deg rotation of your profile).  Personally I'd recommend always using "natural" if your path allows it.  It's not the default simply because there are paths it fails on (like any path where curvature is every zero, which includes any path with straight segments) whereas the "incremental" always works.

**Comment by dan-p3rry** [comment]
Thanks, setting normal=FWD fixed my issue.  Feel free to add my test case a documentation example if you think it will help.

![image](https://github.com/user-attachments/assets/7523ff66-ccd3-4a2a-9519-5e36161cf08f)
